package Mapeamento;
// Generated 18/09/2015 14:58:06 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Cargo generated by hbm2java
 */
public class Cargo  implements java.io.Serializable {


     private int cod;
     private String nome;
     private BigDecimal salariobase;
     private int quantfunc;
     private Set funcionarios = new HashSet(0);

    public Cargo() {
    }

	
    public Cargo(int cod, String nome, BigDecimal salariobase, int quantfunc) {
        this.cod = cod;
        this.nome = nome;
        this.salariobase = salariobase;
        this.quantfunc = quantfunc;
    }
    public Cargo(int cod, String nome, BigDecimal salariobase, int quantfunc, Set funcionarios) {
       this.cod = cod;
       this.nome = nome;
       this.salariobase = salariobase;
       this.quantfunc = quantfunc;
       this.funcionarios = funcionarios;
    }
   
    public int getCod() {
        return this.cod;
    }
    
    public void setCod(int cod) {
        this.cod = cod;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public BigDecimal getSalariobase() {
        return this.salariobase;
    }
    
    public void setSalariobase(BigDecimal salariobase) {
        this.salariobase = salariobase;
    }
    public int getQuantfunc() {
        return this.quantfunc;
    }
    
    public void setQuantfunc(int quantfunc) {
        this.quantfunc = quantfunc;
    }
    public Set getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set funcionarios) {
        this.funcionarios = funcionarios;
    }




}


