package Mapeamento;
// Generated 18/09/2015 14:58:06 by Hibernate Tools 4.3.1



/**
 * DependentesId generated by hbm2java
 */
public class DependentesId  implements java.io.Serializable {


     private String nome;
     private String cpffuncionario;

    public DependentesId() {
    }

    public DependentesId(String nome, String cpffuncionario) {
       this.nome = nome;
       this.cpffuncionario = cpffuncionario;
    }
   
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCpffuncionario() {
        return this.cpffuncionario;
    }
    
    public void setCpffuncionario(String cpffuncionario) {
        this.cpffuncionario = cpffuncionario;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DependentesId) ) return false;
		 DependentesId castOther = ( DependentesId ) other; 
         
		 return ( (this.getNome()==castOther.getNome()) || ( this.getNome()!=null && castOther.getNome()!=null && this.getNome().equals(castOther.getNome()) ) )
 && ( (this.getCpffuncionario()==castOther.getCpffuncionario()) || ( this.getCpffuncionario()!=null && castOther.getCpffuncionario()!=null && this.getCpffuncionario().equals(castOther.getCpffuncionario()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNome() == null ? 0 : this.getNome().hashCode() );
         result = 37 * result + ( getCpffuncionario() == null ? 0 : this.getCpffuncionario().hashCode() );
         return result;
   }   


}


