package Mapeamento;
// Generated 18/09/2015 14:58:06 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Salario generated by hbm2java
 */
public class Salario  implements java.io.Serializable {


     private SalarioId id;
     private Funcionario funcionario;
     private BigDecimal valor;

    public Salario() {
    }

    public Salario(SalarioId id, Funcionario funcionario, BigDecimal valor) {
       this.id = id;
       this.funcionario = funcionario;
       this.valor = valor;
    }
   
    public SalarioId getId() {
        return this.id;
    }
    
    public void setId(SalarioId id) {
        this.id = id;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }




}


