package Mapeamento;
// Generated 18/09/2015 14:58:06 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SalarioId generated by hbm2java
 */
public class SalarioId  implements java.io.Serializable {


     private Date data;
     private String func;

    public SalarioId() {
    }

    public SalarioId(Date data, String func) {
       this.data = data;
       this.func = func;
    }
   
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public String getFunc() {
        return this.func;
    }
    
    public void setFunc(String func) {
        this.func = func;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SalarioId) ) return false;
		 SalarioId castOther = ( SalarioId ) other; 
         
		 return ( (this.getData()==castOther.getData()) || ( this.getData()!=null && castOther.getData()!=null && this.getData().equals(castOther.getData()) ) )
 && ( (this.getFunc()==castOther.getFunc()) || ( this.getFunc()!=null && castOther.getFunc()!=null && this.getFunc().equals(castOther.getFunc()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getData() == null ? 0 : this.getData().hashCode() );
         result = 37 * result + ( getFunc() == null ? 0 : this.getFunc().hashCode() );
         return result;
   }   


}


