package Mapeamento;
// Generated 18/09/2015 14:58:06 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Dependentes generated by hbm2java
 */
public class Dependentes  implements java.io.Serializable {


     private DependentesId id;
     private Funcionario funcionario;
     private char sexo;
     private Date datanasc;
     private String parentesco;

    public Dependentes() {
    }

    public Dependentes(DependentesId id, Funcionario funcionario, char sexo, Date datanasc, String parentesco) {
       this.id = id;
       this.funcionario = funcionario;
       this.sexo = sexo;
       this.datanasc = datanasc;
       this.parentesco = parentesco;
    }
   
    public DependentesId getId() {
        return this.id;
    }
    
    public void setId(DependentesId id) {
        this.id = id;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public char getSexo() {
        return this.sexo;
    }
    
    public void setSexo(char sexo) {
        this.sexo = sexo;
    }
    public Date getDatanasc() {
        return this.datanasc;
    }
    
    public void setDatanasc(Date datanasc) {
        this.datanasc = datanasc;
    }
    public String getParentesco() {
        return this.parentesco;
    }
    
    public void setParentesco(String parentesco) {
        this.parentesco = parentesco;
    }




}


