package Mapeamento;
// Generated 18/09/2015 14:58:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Funcionario generated by hbm2java
 */
public class Funcionario  implements java.io.Serializable {


     private String cpf;
     private Cargo cargo;
     private String nome;
     private String endereco;
     private String telefone;
     private Set dependenteses = new HashSet(0);
     private Set salarios = new HashSet(0);

    public Funcionario() {
    }

	
    public Funcionario(String cpf, Cargo cargo, String nome, String endereco, String telefone) {
        this.cpf = cpf;
        this.cargo = cargo;
        this.nome = nome;
        this.endereco = endereco;
        this.telefone = telefone;
    }
    public Funcionario(String cpf, Cargo cargo, String nome, String endereco, String telefone, Set dependenteses, Set salarios) {
       this.cpf = cpf;
       this.cargo = cargo;
       this.nome = nome;
       this.endereco = endereco;
       this.telefone = telefone;
       this.dependenteses = dependenteses;
       this.salarios = salarios;
    }
   
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public Cargo getCargo() {
        return this.cargo;
    }
    
    public void setCargo(Cargo cargo) {
        this.cargo = cargo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public Set getDependenteses() {
        return this.dependenteses;
    }
    
    public void setDependenteses(Set dependenteses) {
        this.dependenteses = dependenteses;
    }
    public Set getSalarios() {
        return this.salarios;
    }
    
    public void setSalarios(Set salarios) {
        this.salarios = salarios;
    }




}


